-
  name: 'Create nodes'
  uriPattern: 'multiplenodecreation/create'
  defaults:
    '@controller': 'Node'
    '@package': 'NeosRulez.Neos.MultipleNodeCreation'
    '@action': 'create'
    '@format': 'json'
  appendExceedingArguments: true
