Neos:
  Flow:
    mvc:
      routes:
        NeosRulez.Neos.MultipleNodeCreation:
          position: 'start'
    security:
      authentication:
        providers:
          'Neos.Neos:Backend':
            requestPatterns:
              'NeosRulez.Neos.MultipleNodeCreation:Commands':
                pattern: ControllerObjectName
                patternOptions:
                  controllerObjectNamePattern: 'NeosRulez\Neos\MultipleNodeCreation\Controller\.*'
  Neos:
    Ui:
      resources:
        stylesheets:
          'NeosRulez.Neos.MultipleNodeCreation':
            resource: '${"resource://NeosRulez.Neos.MultipleNodeCreation/Public/Plugin.css"}'
        javascript:
          'NeosRulez.Neos.MultipleNodeCreation':
            resource: '${"resource://NeosRulez.Neos.MultipleNodeCreation/Public/Plugin.js"}'
      frontendConfiguration:
        'NeosRulez.Neos.MultipleNodeCreation:MinimumRows': '${Configuration.setting(''NeosRulez.Neos.MultipleNodeCreation.site.minRows'')}'
    userInterface:
      translation:
        autoInclude:
          NeosRulez.Neos.MultipleNodeCreation:
            - Main
NeosRulez:
  Neos:
    MultipleNodeCreation:
      site:
        minRows: 5
